# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amiibo', '0002_amiibo_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amiibo',
            name='owner',
        ),
    ]
