# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amiibo', '0004_amiibo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amiibo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
