# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amiibo', '0005_auto_20160528_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='amiibo',
            name='price',
            field=models.CharField(default=12.99, max_length=6),
            preserve_default=False,
        ),
    ]
