# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amiibo', '0007_auto_20160717_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='amiibo',
            name='gtotals',
            field=models.FloatField(default=0),
        ),
    ]
